
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-organic-w24-6pm-1
owner: ucsb-cs156-w24
repo_name: proj-organic-w24-6pm-1
pull_requests: [{"author":{"id":"U_kgDOB0qFUw","is_bot":false,"login":"vcnardi524","name":"victor Nardi"},"headRefName":"Victor-School-IndexPage-dev","number":74,"title":"Victor school index page dev","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/74"},{"author":{"id":"U_kgDOB3Dokw","is_bot":false,"login":"jenil-prajapati","name":""},"headRefName":"Jenil-School-Get-dev2","number":73,"title":"Jenil school get one and get all","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/73"},{"author":{"id":"U_kgDOB0qFUw","is_bot":false,"login":"vcnardi524","name":"victor Nardi"},"headRefName":"Victor-School-Table-dev","number":68,"title":"Victor school table and school utils component in addition to the storybook.","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/68"}]
