
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-organic-w24-6pm-1
owner: ucsb-cs156-w24
repo_name: proj-organic-w24-6pm-1
pull_requests: [{"author":{"id":"U_kgDOB3E2LA","is_bot":false,"login":"sanilkatula","name":""},"headRefName":"Sanil-TimestampBug","number":47,"title":"sk - resolved [BUG]: Last Online in User Profile Defaults to Wrong Date","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/47"},{"author":{"id":"MDQ6VXNlcjY4Nzc4MDE5","is_bot":false,"login":"phillylim","name":"Philly Lim"},"headRefName":"UserViewCourse","number":44,"title":"PL- [Feature] User view course","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/44"},{"author":{"id":"U_kgDOB3E2LA","is_bot":false,"login":"sanilkatula","name":""},"headRefName":"Sanil-dev","number":43,"title":"sk - added [FEATURE]: Instructors can create courses","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/43"},{"author":{"id":"MDQ6VXNlcjY4Nzc4MDE5","is_bot":false,"login":"phillylim","name":"Philly Lim"},"headRefName":"AdminPopupConfirmation","number":42,"title":"PL - Feature Implementation: Admin popup confirmation","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/42"},{"author":{"id":"MDQ6VXNlcjY4Nzc4MDE5","is_bot":false,"login":"phillylim","name":"Philly Lim"},"headRefName":"IconBugFix","number":41,"title":"PL - Icon bug fix","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/41"},{"author":{"id":"MDQ6VXNlcjY4Nzc4MDE5","is_bot":false,"login":"phillylim","name":"Philly Lim"},"headRefName":"BugFixFooter","number":40,"title":"PL - Bug fix footer","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/40"},{"author":{"id":"MDQ6VXNlcjY4Nzc4MDE5","is_bot":false,"login":"phillylim","name":"Philly Lim"},"headRefName":"PhilllyCourseStaffForm","number":39,"title":"PL - Adds form component, storybook page, and 100% test and mutation coverage","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/39"}]
