
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-organic-w24-6pm-1
owner: ucsb-cs156-w24
repo_name: proj-organic-w24-6pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4Nzc4MDE5","is_bot":false,"login":"phillylim","name":"Philly Lim"},"headRefName":"BugFixFooter","number":40,"title":"Bug fix footer","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/40"},{"author":{"id":"MDQ6VXNlcjY4Nzc4MDE5","is_bot":false,"login":"phillylim","name":"Philly Lim"},"headRefName":"PhilllyCourseStaffForm","number":39,"title":"Adds form component, storybook page, and 100% test and mutation coverage","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/39"},{"author":{"id":"U_kgDOB3E2LA","is_bot":false,"login":"sanilkatula","name":""},"headRefName":"Sanil-dev","number":38,"title":" sk - added FEATURE: Instructors can create courses","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-1/pull/38"}]
